version: "3.8"

services:
  backend:
    restart: always
    env_file:
      - .env
    build: ./backend
    ports:
      - 5001:5001
    volumes:
      - "./backend:/app"
    command: uvicorn app.src.main:app --reload --host 0.0.0.0 --port 5001
    depends_on:
      - db
      - migration
  migration:
    build: ./backend
    volumes:
      - "./backend/app:/app"
    command: alembic upgrade head
    depends_on:
      - db
  frontend:
    restart: always
    build: ./frontend
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - 8080:8080
  db:
    restart: always
    image: postgres:latest
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
volumes:
  app-db-data:
